### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by Ygarr** [Murph9/RallyGame#2]
win10
gradle runSurvival

Sep 11, 2022 5:44:14 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetNotFoundException: models/track1_2.blend.glb
        at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:371)
        at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:417)
        at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:421)
        at rallygame.car.data.CarModelData.<init>(CarModelData.java:18)
        at rallygame.car.data.CarDataLoader.loadFromModel(CarDataLoader.java:90)
        at rallygame.car.data.CarDataLoader.get(CarDataLoader.java:80)
        at rallygame.car.CarManager.loadData(CarManager.java:81)
        at rallygame.car.CarManager.loadData(CarManager.java:71)
        at rallygame.car.CarManager.addCar(CarManager.java:92)
        at rallygame.drive.DriveBase.initialize(DriveBase.java:65)
        at survival.Drive.initialize(Drive.java:23)
        at com.jme3.app.state.BaseAppState.initialize(BaseAppState.java:132)
        at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:317)
        at com.jme3.app.state.AppStateManager.update(AppStateManager.java:347)
        at com.jme3.app.SimpleApplication.update(SimpleApplication.java:255)
        at survival.SurvivalApp.update(SurvivalApp.java:81)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
        at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
        at java.base/java.lang.Thread.run(Thread.java:833)

rallygame.car.CarManager cleanup
cleanup() world: tiled flat world rootNode rm(0)

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "jME3 Main"

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 18s
4 actionable tasks: 2 executed, 2 up-to-date

**Comment by Ygarr** [comment]
![rally2022-09-11_17-52](https://user-images.githubusercontent.com/14309871/189534279-850fac2d-38ea-4476-9fc6-140e60ec3860.png)
![run2022-09-11_17-53](https://user-images.githubusercontent.com/14309871/189534292-6bf7a3eb-92c8-41f0-8e1d-883360fca84f.png)

**Comment by Murph9** [comment]
![image](https://user-images.githubusercontent.com/7650004/189550757-ae33171a-c772-4180-b619-78114016cd04.png)

From the readme https://github.com/Murph9/RallyGame/blob/master/README.md

Also if you just want to play it the download is here: https://www.murph9.com/mygames/

**Comment by Ygarr** [comment]
I thought that trouble not in blender, cause I set blender path. But anyway got missing asset
![2022-09-12_09-51](https://user-images.githubusercontent.com/14309871/189590888-e47e475a-fa8e-4c45-9a9e-d4e3d0ad91f9.png)

**Comment by Murph9** [comment]
Did the task `convertAllBlendFiles` actually run?

**Comment by Ygarr** [comment]
Yes it`s succeful passed:

```
\RallyGame> gradle convertAllBlendFiles

> Task :convertAllBlendFiles
Running on: windows 10
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\fullcity\base.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\fullcity\building.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\fullcity\cross.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\fullcity\leftrightT.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\fullcity\leftT.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\fullcity\rightT.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\fullcity\straight.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\base.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\busbus.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\busbus_wheel.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\car4.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\car4raid_1.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\debug.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\extreme_green.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\fa_racing.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\Mazda_121_Metro.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\Mazda_121_Metro_wheel.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\muscle.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\na_2_out.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\na_w_1_out.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\ricer.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\rocket1_1.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\rt_ryukyu.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\sa_hummer.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\sa_hummer_wheel.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\screamin_eagle.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\track1_2.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\ultra_64.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\Wagon.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\Wagon_Wheel.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\wheel1.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\wheel2.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\wheel3.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\models\wheel_raid_1.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\objects\tree_0.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\objects\tree_1.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\objects\tree_2.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\objects\tree_3.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\objects\tree_4.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\objects\tree_5.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\objects\tree_6.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\block_fort.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\carpark.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\dragstrip.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\duct.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\garage.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\garage_2.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\lakelooproad.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\multidragstrip.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\mycity.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\rainbow_road.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\raleigh.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\real_road.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\slope_test.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\spa_v2.1.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\surfaceTest.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\track2.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\staticworld\unbenannt_track.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\city.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\cliff.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\ditch.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\floating\light.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\floating.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\mainroad.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\rocks.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\simple.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\simple2.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\track.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\underground.blend
Running: C:\Users\user\SHARE\GAMES\RallyGame\src\main\resources\wb\valley.blend

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 25s
1 actionable task: 1 executed
```
But after that got screen with:
```
Uncaught exception thrown in Thread[jME3 Main,5,main]
AssetNotFoundException: models/track1_2.blend.glb
```

**Comment by Murph9** [comment]
I can delete that file in `RallyGame\src\main\resources\models` and it will regenerate it and load it:
```
PS C:\projects\RallyGame> .\gradlew.bat runSurvival
...
generated is newer for: sa_hummer.blend
generated is newer for: sa_hummer_wheel.blend
generated is newer for: screamin_eagle.blend
Running: S:\projects\RallyGame\src\main\resources\models\track1_2.blend
generated is newer for: ultra_64.blend
generated is newer for: Wagon.blend
...
```
To the application working. (if i disable the task and do the same thing the file does not load)


I have cloned the repo and ran these commands and it worked:
```
git clone https://github.com/Murph9/RallyGame
cd .\RallyGame\
.\gradlew.bat runSurvival
```
And the game loads fine.

Seems to be your computer is not doing something right.

**Comment by Ygarr** [comment]
Ok, may be java versions incompatible. When doing `.\gradlew.bat runSurvival`
 got 
` java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7`

```
 java -version
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode, sharing)
```
